#!/bin/bash
echo "===== 通过普通用户部署 ====="
echo ""
echo "由于服务器禁用 root 直接登录，请使用以下方式："
echo ""
echo "方式一：配置本地私钥"
echo "请提供与公钥对应的私钥文件路径，或创建 SSH 配置"
echo ""
echo "方式二：手动部署（推荐）"
echo "请执行以下命令："
echo ""
echo "1. SSH 登录（使用你的普通用户）:"
echo "   ssh -i ~/.ssh/your_key admin@47.236.193.197"
echo ""
echo "2. 切换到 root:"
echo "   sudo -i"
echo ""
echo "3. 部署前台:"
echo "   cd /var/www/indigenex-website/frontend"
echo "   rm -rf .next node_modules"
echo "   npm install"
echo "   npm run build"
echo "   PORT=3000 pm2 start npm --name 'indigenex-frontend' -- start"
echo "   pm2 save"
echo "   pm2 status"
echo ""
echo "或者，如果你有私钥文件，请告诉我路径，我可以配置自动部署。"
