#!/bin/bash
echo "在服务器上以 root 身份执行："
echo ""
echo "sudo -i"
echo ""
echo "cd /var/www/indigenex-website/frontend"
echo ""
echo "# 1. 删除 Mac 版本的 node_modules"
echo "rm -rf node_modules package-lock.json"
echo ""
echo "# 2. 修改目录权限"
echo "chown -R root:root /var/www/indigenex-website/frontend"
echo ""
echo "# 3. 安装 Linux 版本的依赖"
echo "npm install"
echo ""
echo "# 4. 构建"
echo "npm run build"
echo ""
echo "# 5. 启动服务"
echo "PORT=3000 pm2 start npm --name 'indigenex-frontend' -- start"
echo "pm2 save"
echo "pm2 status"
