#!/bin/bash
echo "在服务器上执行以下命令："
echo ""
echo "# 1. 强制终止所有 node/npm 进程"
echo "sudo pkill -9 -f node"
echo "sudo pkill -9 -f npm"
echo ""
echo "# 2. 清理并重新安装（仅生产依赖）"
echo "cd /var/www/indigenex-website/frontend"
echo "sudo rm -rf node_modules .next"
echo "sudo npm install --production"
echo ""
echo "# 3. 启动"
echo "sudo PORT=3000 pm2 start npm --name indigenex-frontend -- start"
echo "sudo pm2 save"
echo "sudo pm2 status"
